### ISSUE TITLE
How to execute and get queries back

### ISSUE THREAD

**Issue by adriens** [openanalytics/redmineR#1]
Hi, i've just discovered your project and i want to give it a try as i need to perform some reporting on our redmine. Currenlty i have predefied queries (with queries id) i'd like to run form R to perform a nice looking report from Rmarkdown, but for now, i wonder if your lib makes this possible ?

Thank you in advance for your answer.

**Comment by mnazarov** [comment]
Hi, thank you for you interest. This is possible with the following code:
First, get the list of all existing queries with IDs with `redmine_search_id(endpoint = "queries")` (you can also specify `name` to filter by name). Then supply the desired query ID to the `redmine_issues(query_id = ...)` call.

**Comment by adriens** [comment]
Great ! Could you please add a fully runnable code sample the same way you did for projects on the README.md ?..as it could interest other peoples ;-p

**Comment by mnazarov** [comment]
Sure, added example in the `README.md`.

**Comment by adriens** [comment]
WOW, thanks a lot !!!
