### ISSUE TITLE
package does not work when the URL is https://sampleredmineapp.com/redmine

### ISSUE THREAD

**Issue by tarkomatas** [openanalytics/redmineR#2]
Hello!

First of all I would like to thank you for creating and publishing this useful package.

Unfortunately It doesn't works when I try to connect to a Redmine server which has a URL like this: "https://sampleredmineapp.com/redmine"

The error message is always the same: "Error: API did not return JSON"

Here is the code that we tried:

```
Sys.setenv("REDMINE_URL" = "https://task.ppke.hu/redmine")
Sys.setenv("REDMINE_TOKEN" = "****************")  # we used a valid token of course

redmine_projects()
#Error: API did not return JSON
```

It would really helps us a lot If you can fix this. 

Regards,
Tamas

**Comment by mnazarov** [comment]
Thanks for reporting! I can see the cause of the problem, and will fix it shortly.
