### ISSUE TITLE
Using redmineR on Easyredmine

### ISSUE THREAD

**Issue by kianweelee** [openanalytics/redmineR#4]
Good day,

Can I kindly ask if this R package will work on EasyRedmine?

I tried:
```R
library(redmineR)

# Setting Redmine environment 
Sys.setenv("REDMINE_URL" = "https://redmine-x-test.x.org/")
Sys.setenv("REDMINE_TOKEN" = "xx")

redmine_projects()
```
And got:

```
Error in `[<-.data.frame`(`*tmp*`, atomicCols, value = list(id = c(37L,  : 
  replacement element 15 has 5 rows, need 6
```

I have look around on stackoverflow and Rstudio community forums but can't seem to find a solution for this.

**Comment by kianweelee** [comment]
Used redmine_list_projects()

**Comment by mnazarov** [comment]
sorry for not responding earlier, I don't have access to a easyredmine instance, but from their website it seems to be compatible.
Good to know that you found a solution.

**Comment by kianweelee** [comment]
No worries! Thanks for the help though!
